<?xml version="1.0"?>
<robot name="stupidbot_gazebo" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- Set up for all model plugins -->
	<xacro:macro name="stupidbot_gazebo">
	
	<!-- Include properties file -->
	<xacro:include filename="$(find stupidbot_description)/urdf/stupidbot_properties.urdf.xacro"/>
		<gazebo>
			<!-- Differential Drive Plugin -->
			<plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
				<alwaysOn>true</alwaysOn>
				<updateRate>100.0</updateRate>
				<leftJoint>left_wheel_joint</leftJoint>
				<rightJoint>right_wheel_joint</rightJoint>
				<wheelSeparation>${chassis_width + 0.02}</wheelSeparation>
				<wheelDiameter>0.12</wheelDiameter>
				<wheelTorque>10</wheelTorque>
				<robotBaseFrame>base_footprint</robotBaseFrame>
				<odometryFrame>map</odometryFrame>
				<publishWheelJointState>true</publishWheelJointState>
				<publishWheelTF>true</publishWheelTF>
			</plugin>

			<!-- Ros Control Plugin -->
			<plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so"/>

			<!-- Joint State Publisher for non-actuated joints -->
			<!-- Place any joints we want published in the jointName tag -->
			<plugin name="gazebo_ros_joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
				<jointName>left_caster_swivel_joint, left_caster_joint, right_caster_swivel_joint, right_caster_joint</jointName>
			</plugin>
			
		</gazebo>
	</xacro:macro>
</robot>
