<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- Properties file -->
	<xacro:include filename="$(find stupidbot_description)/urdf/stupidbot_properties.urdf.xacro"/>

	<!-- Full caster description including swivel and wheel -->
	<xacro:macro name="caster" params="parent lr reflectY">

		<!-- Caster swivel -->
		<link name="${lr}_caster_swivel">
			<visual>
				<geometry>
					<cylinder length="0.001" radius="${caster_radius}"/>
				</geometry>
				<material name="black"/>
			</visual>
			<inertial>
				<mass value="0.001"/>
				<inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
			</inertial>
			<collision>
				<geometry>
					<cylinder length="0.001" radius="${caster_radius}"/>
				</geometry>
			</collision>
			<gazebo reference="${lr}_caster_swivel"/>
		</link>

		<!-- Caster wheel -->
		<link name="${lr}_caster_wheel">
			<visual>
				<geometry>
					<cylinder length="${caster_width}" radius="${caster_radius}"/>
				</geometry>
				<origin rpy="1.57057 0 0"/>
				<material name="black"/>
			</visual>
			<inertial>
				<mass value="${caster_mass}"/>
				<inertia ixx="${caster_ixx}" ixy="0.0" ixz="0.0" iyy="${caster_iyy}" iyz="0.0" izz="${caster_izz}"/>
			</inertial>
			<collision>
				<geometry>
					<cylinder length="${caster_width}" radius="${caster_radius}"/>
				</geometry>
				<origin rpy="1.57057 0 0"/>
			</collision>
		</link>

		<!-- Set Gazebo physics parameters -->
		<gazebo reference="${lr}_caster_wheel">
			<mu1>0.7</mu1>
			<mu2>0.7</mu2>
			<kp>10000000</kp>
			<kd>100.0</kd>
			<minDepth>0.001</minDepth>
		</gazebo>

		<!-- Joint connecting base and caster swivel -->
		<joint name="${lr}_caster_swivel_joint" type="revolute">
			<parent link="${parent}"/>
			<child link="${lr}_caster_swivel"/>
			<axis xyz="0 0 1"/>
			<origin xyz="${chassis_length/4} ${reflectY * caster_y_displacement} -${chassis_height/2 + 0.005}"/>
			<limit upper="3.1415" lower="-3.1415" effort="100.0" velocity="0.0"/>
		</joint>

		<gazebo reference="${lr}_caster_swivel_joint"/>

		<!-- Joint connecting caster swivel and caster -->
		<joint name="${lr}_caster_joint" type="continuous">
			<parent link="${lr}_caster_swivel"/>
			<child link="${lr}_caster_wheel"/>
			<axis xyz="0 1 0"/>
			<origin xyz="0 0 -${caster_radius + 0.003}"/>
			<limit effort="100.0" velocity="0.0"/>
		</joint>

		<gazebo reference="${lr}_caster_joint"/>

	</xacro:macro>
</robot>


