<?xml version="1.0"?>
<robot>

	<!-- Mathematical constants -->
	<property name="M_PI" value="3.14159"/>
	<!-- Chassis/body properties -->
	<property name="chassis_length" value="0.2"/>
	<property name="chassis_width" value="0.2"/>
	<property name="chassis_height" value="0.05"/>
	<property name="chassis_mass" value="40.0"/>
	<property name="chassis_ixx" value="${chassis_mass*(chassis_length*chassis_length + chassis_height*chassis_height)/12}"/>
	<property name="chassis_iyy" value="${chassis_mass*(chassis_width*chassis_width + chassis_height*chassis_height)/12}"/>
	<property name="chassis_izz" value="${chassis_mass*(chassis_length*chassis_length + chassis_width*chassis_width)/12}"/>

	<!-- Wheel properties -->
	<property name="wheel_mass" value="10.0"/>
	<property name="wheel_radius" value="0.06"/>
	<property name="wheel_width" value="0.04"/>
	<property name="wheel_ixx" value="${(wheel_mass*(3*wheel_radius*wheel_radius + wheel_width*wheel_width))/12}"/>
	<property name="wheel_iyy" value="${(wheel_mass*(3*wheel_radius*wheel_radius + wheel_width*wheel_width))/12}"/>
	<property name="wheel_izz" value="${(wheel_mass*wheel_radius*wheel_radius)/2}"/>

	<!-- Camera properties -->
	<property name="camera_mass" value="0.5"/>
	<property name="camera_length" value="0.02"/>
	<property name="camera_width" value="0.02"/>
	<property name="camera_height" value="0.02"/>
	<property name="camera_x_pos" value="${chassis_length/2 - camera_length/2}"/>
	<property name="camera_y_pos" value="-${chassis_width/4}"/>
	<property name="camera_z_pos" value="${chassis_height/2 + camera_height/2}"/>
	<property name="camera_ixx" value="${camera_mass*(camera_length*camera_length + camera_height*camera_height)/12}"/>
	<property name="camera_iyy" value="${camera_mass*(camera_width*camera_width + camera_height*camera_height)/12}"/>
	<property name="camera_izz" value="${camera_mass*(camera_length*camera_length + camera_width*camera_width)/12}"/>

	<!-- Caster properties -->
	<property name="caster_width" value="0.015"/>
	<property name="caster_radius" value="0.012"/>
	<property name="caster_mass" value="5.0"/>
	<property name="caster_ixx" value="${caster_mass*(3*caster_radius*caster_radius + caster_width*caster_width)/12}"/>
	<property name="caster_iyy" value="${caster_mass*(3*caster_radius*caster_radius + caster_width*caster_width)/12}"/>
	<property name="caster_izz" value="${caster_mass*(caster_radius*caster_radius)/2}"/>
	<property name="caster_y_displacement" value="${chassis_width/4}"/>

</robot>