<?xml version="1.0"?>
<robot name="wheels" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<!-- Include chassis properties for positioning joints -->
	<xacro:include filename="$(find stupidbot_description)/urdf/stupidbot_properties.urdf.xacro"/>

	<!-- Wheel properties -->
	<xacro:property name="wheel_mass" value="10.0"/>
	<xacro:property name="wheel_radius" value="0.06"/>
	<xacro:property name="wheel_width" value="0.04"/>

	<xacro:macro name="wheel" params="lr parent reflectY">
		
		<!-- Wheel link description -->
		<link name="${lr}_wheel">
			<visual>
				<geometry>
					<cylinder length="${wheel_width}" radius="${wheel_radius}"/>
				</geometry>
				<origin rpy="1.57057 0 0"/>
				<material name="black"/>
			</visual>
			<inertial>
				<mass value="${wheel_mass}"/>
				<inertia ixx="${(wheel_mass*(3*wheel_radius*wheel_radius + wheel_width*wheel_width))/12}" ixy="0.0" ixz="0.0" iyy="${(wheel_mass*(3*wheel_radius*wheel_radius + wheel_width*wheel_width))/12}" iyz="0.0" izz="${(wheel_mass*wheel_radius*wheel_radius)/2}"/>
			</inertial>
			<collision>
				<geometry>
					<cylinder length="${wheel_width}" radius="${wheel_radius}"/>
				</geometry>
				<origin rpy="1.57057 0 0"/>
			</collision>
			<gazebo reference="${lr}_wheel">
				<mu1 value="1.0"/>
				<mu2 value="1.0"/>
				<kp  value="10000000.0" />
      			<kd  value="100.0" />
			</gazebo>
		</link>

		<!-- Joint connecting wheel and base link -->
		<joint name="${lr}_wheel_joint" type="continuous">
			<parent link="${parent}"/>
			<child link="${lr}_wheel"/>
			<axis xyz="0 1 0"/>
			<origin xyz="-${chassis_length/4} ${reflectY * (chassis_width/2 + wheel_width/2)} 0"/>
			<limit effort="100" velocity="0.0"/>
			<gazebo reference="${lr}_wheel_joint"/>
		</joint>

		<!-- Transmission for wheel joint -->
		<transmission name="${lr}_wheel_trans">
			<type>transmission_interface/SimpleTransmission</type>
			<joint name="${lr}_wheel_joint">
				<hardwareInterface>EffortJointInterface</hardwareInterface>
			</joint>
			<actuator name="${lr}_motor">
				<mechanicalReduction>1</mechanicalReduction>
			</actuator>
		</transmission>

	</xacro:macro>
</robot>

