<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
	<xacro:macro name="stupidbot_chassis">

	<xacro:include filename="$(find stupidbot_description)/urdf/stupidbot_properties.urdf.xacro"/>

		<material name="black">
			<color rgba="0 0 0 1"/>
		</material>

		<!-- Base link, center of chassis and body -->
		<link name="base_link">
			<visual>
				<geometry>
					<box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
				</geometry>
			</visual>
			<inertial>
				<mass value="20"/>
				<inertia ixx="0.421" ixy="0.0" ixz="0.0" iyy="0.0108" iyz="0.0" izz="0.521"/>
			</inertial>
			<collision>
				<geometry>
					<box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
				</geometry>
				<origin xyz="0 0 0" rpy="0 0 0"/>
			</collision>
			<gazebo reference="base_link"/>
		</link>

		<!-- Right wheel link -->
		<link name="right_wheel">
			<visual>
				<geometry>
					<cylinder length="${wheel_width}" radius="${wheel_radius}"/>
				</geometry>
				<origin rpy="-1.57057 0 0"/>
				<material name="black"/>
			</visual>
			<inertial>
				<mass value="1.0"/>
				<inertia ixx="0.00019" ixy="0.0" ixz="0.0" iyy="0.00019" iyz="0.0" izz="0.00031"/>
			</inertial>
			<collision>
				<geometry>
					<cylinder length="${wheel_width}" radius="${wheel_radius}"/>
				</geometry>
				<origin rpy="1.57057 0 0"/>
			</collision>
			<gazebo reference="right_front_wheel">
				<mu1 value="0.7"/>
				<mu2 value="0.7"/>
				<fdir1 value="1 0 0"/>
				<kp  value="10000000.0" />
      			<kd  value="1.0" />
			</gazebo>
		</link>

		<!-- Left wheel link -->
		<link name="left_wheel">
			<visual>
				<geometry>
					<cylinder length="${wheel_width}" radius="${wheel_radius}"/>
				</geometry>
				<origin rpy="1.57057 0 0"/>
				<material name="black"/>
			</visual>
			<inertial>
				<mass value="1.0"/>
				<inertia ixx="0.00019" ixy="0.0" ixz="0.0" iyy="0.00019" iyz="0.0" izz="0.00031"/>
			</inertial>
			<collision>
				<geometry>
					<cylinder length="${wheel_width}" radius="${wheel_radius}"/>
				</geometry>
				<origin rpy="1.57057 0 0"/>
			</collision>
			<gazebo reference="left_front_wheel">
				<mu1 value="0.7"/>
				<mu2 value="0.7"/>
				<fdir1 value="1 0 0"/>
				<kp  value="10000000.0" />
      			<kd  value="1.0" />
			</gazebo>
		</link>

		<!-- Front caster wheel -->
		<link name="front_caster">
			<visual>
				<geometry>
					<cylinder length="${caster_width}" radius="${caster_radius}"/>
				</geometry>
				<origin rpy="1.57057 0 0"/>
				<material name="black"/>
			</visual>
			<inertial>
				<mass value="0.5"/>
				<inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.0001"/>
			</inertial>
			<collision>
				<geometry>
					<cylinder length="${caster_width}" radius="${caster_radius}"/>
				</geometry>
				<origin rpy="1.57057 0 0"/>
			</collision>
			<gazebo reference="caster_wheel">
				<mu1 value="0.7"/>
				<mu2 value="0.7"/>
				<fdir1 value="1 0 0"/>
				<kp value="10000000.0"/>
				<kd value="1.0" />
			</gazebo>
		</link>

		<link name="caster_swivel">
			<visual>
				<geometry>
					<cylinder length="0.001" radius="${caster_width}"/>
				</geometry>
				<material name="black"/>
			</visual>
			<inertial>
				<mass value="0.2"/>
				<inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001"/>
			</inertial>
			<collision>
				<geometry>
					<cylinder length="0.001" radius="${caster_width}"/>
				</geometry>
			</collision>
			<gazebo reference="caster_swivel">
				<mu1 value="0.7"/>
				<mu2 value="0.7"/>
				<fdir1 value="1 0 0"/>
				<kp value="10000000.0"/>
				<kd value="1.0" />
			</gazebo>
		</link>
		
		<!-- Joint from base to right front wheel -->
		<joint name="base_to_right_wheel" type="continuous">
			<parent link="base_link"/>
			<child link="right_wheel"/>
			<axis xyz="0 1 0"/>
			<origin xyz="0 ${chassis_width/2 + wheel_width/2} 0"/>
			<limit effort="100" velocity="0.0"/>
			<gazebo reference="right_wheel_joint"/>
		</joint>

		<!-- Joint from base to left front wheel -->
		<joint name="base_to_left_wheel" type="continuous">
			<parent link="base_link"/>
			<child link="left_wheel"/>
			<axis xyz="0 1 0"/>
			<origin xyz="0 -${chassis_width/2 + wheel_width/2} 0"/>
			<limit effort="100" velocity="0.0"/>
			<gazebo reference="left_wheel_joint"/>
		</joint>

		<!-- Joint from base to caster swivel -->
		<joint name="base_to_caster_swivel" type="continuous">
			<parent link="base_link"/>
			<child link="caster_swivel"/>
			<axis xyz="0 0 1"/>
			<origin xyz="${chassis_length - caster_radius} 0 -${chassis_height/2}"/>
			<gazebo reference="caster_swivel_joint"/>
		</joint>

		<!-- Joint from caster swivel to caster -->
		<joint name="caster_wheel_joint" type="continuous">
			<parent link="caster_swivel"/>
			<child link="front_caster"/>
			<axis xyz="0 1 0"/>
			<origin xyz="0 0 -${caster_radius}"/>
			<gazebo reference="caster_joint"/>
		</joint>

		<transmission name="right_wheel_joint_trans">
			<type>transmission_interface/SimpleTransmission</type>
			<joint name="base_to_right_wheel">
				<hardwareInterface>EffortJointInterface</hardwareInterface>
			</joint>
			<actuator name="right_wheel_joint_motor">
				<hardwareInterface>EffortJointInterface</hardwareInterface>
				<mechanicalReduction>1</mechanicalReduction>
			</actuator>
		</transmission>

		<transmission name="left_wheel_joint_trans">
			<type>transmission_interface/SimpleTransmission</type>
			<joint name="base_to_left_wheel">
				<hardwareInterface>EffortJointInterface</hardwareInterface>
			</joint>
			<actuator name="left_wheel_joint_motor">
				<hardwareInterface>EffortJointInterface</hardwareInterface>
				<mechanicalReduction>1</mechanicalReduction>
			</actuator>
		</transmission>

	</xacro:macro>
</robot>