<?xml version="1.0"?>
<robot name="stupidbot_gazebo" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<!-- Differential Drive -->
	<xacro:macro name="differential_skid">
	<xacro:include filename="$(find stupidbot_description)/urdf/stupidbot_properties.urdf.xacro"/>
		<gazebo>
			<plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
				<alwaysOn>true</alwaysOn>
				<updateRate>100.0</updateRate>
				<leftJoint>left_wheel_joint</leftJoint>
				<rightJoint>right_wheel_joint</rightJoint>
				<wheelSeparation>${chassis_width + 0.02}</wheelSeparation>
				<wheelDiameter>0.12</wheelDiameter>
				<wheelTorque>10</wheelTorque>
				<robotBaseFrame>base_footprint</robotBaseFrame>
				<odometryFrame>map</odometryFrame>
				<publishWheelJointState>true</publishWheelJointState>
				<publishWheelTF>true</publishWheelTF>
			</plugin>
			<plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so"/>
			<plugin name="gazebo_ros_joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
				<jointName>front_caster_swivel_joint, front_caster_joint</jointName>
			</plugin>
		</gazebo>
	</xacro:macro>
</robot>
