<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:include filename="$(find stupidbot_description)/urdf/stupidbot_properties.urdf.xacro"/>

	<!-- Caster constant properties -->
	<xacro:property name="caster_width" value="0.015"/>
	<xacro:property name="caster_radius" value="0.016"/>
	<xacro:property name="caster_mass" value="8.0"/>
	<xacro:property name="caster_ixx" value="${caster_mass*(3*caster_radius*caster_radius + caster_width*caster_width)/12}"/>
	<xacro:property name="caster_iyy" value="${caster_mass*(caster_radius*caster_radius)/2}"/>
	<xacro:property name="caster_izz" value="${caster_mass*(3*caster_radius*caster_radius + caster_width*caster_width)/12}"/>

	<xacro:macro name="caster" params="parent fb reflectX">

		<!-- Caster swivel -->
		<link name="${fb}_caster_swivel">
			<visual>
				<geometry>
					<cylinder length="0.001" radius="${caster_radius}"/>
				</geometry>
				<material name="black"/>
			</visual>
			<inertial>
				<mass value="0.001"/>
				<inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
			</inertial>
			<collision>
				<geometry>
					<cylinder length="0.001" radius="${caster_radius}"/>
				</geometry>
			</collision>
			<gazebo reference="${fb}_caster_swivel"/>
		</link>

		<!-- Caster wheel -->
		<link name="${fb}_caster_wheel">
			<visual>
				<geometry>
					<cylinder length="${caster_width}" radius="${caster_radius}"/>
				</geometry>
				<origin rpy="1.57057 0 0"/>
				<material name="black"/>
			</visual>
			<inertial>
				<mass value="${caster_mass}"/>
				<inertia ixx="${caster_ixx}" ixy="0.0" ixz="0.0" iyy="${caster_iyy}" iyz="0.0" izz="${caster_izz}"/>
			</inertial>
			<collision>
				<geometry>
					<cylinder length="${caster_width}" radius="${caster_radius}"/>
				</geometry>
				<origin rpy="1.57057 0 0"/>
			</collision>
			<gazebo reference="${fb}_caster_wheel">
				<mu1 value="0.0"/>
				<mu2 value="0.0"/>
				<kp value="1000000.0"/>
				<kd value="100.0"/>
			</gazebo>
		</link>

		<!-- Joint connecting base and caster swivel -->
		<joint name="${fb}_caster_swivel_joint" type="revolute">
			<parent link="${parent}"/>
			<child link="${fb}_caster_swivel"/>
			<axis xyz="0 0 1"/>
			<origin xyz="${reflectX*chassis_length/4} 0 -${chassis_height/2 + 0.005}"/>
			<limit upper="1.57057" lower="-1.57057" effort="100.0" velocity="0.0"/>
			<gazebo reference="${fb}_caster_swivel_joint"/>
		</joint>

		<!-- Joint connecting caster swivel and caster -->
		<joint name="${fb}_caster_joint" type="continuous">
			<parent link="${fb}_caster_swivel"/>
			<child link="${fb}_caster_wheel"/>
			<axis xyz="0 1 0"/>
			<origin xyz="0 0 -${caster_radius + 0.003}"/>
			<limit effort="100.0" velocity="0.0"/>
			<dynamics damping="1.0"/>
			<gazebo reference="${fb}_caster_joint"/>
		</joint>

	</xacro:macro>
</robot>


