<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- Include chassis properties for positioning joints -->
	<xacro:include filename="$(find stupidbot_description)/urdf/stupidbot_properties.urdf.xacro"/>

	<!-- Full description macro for wheel including transmissions, etc -->
	<xacro:macro name="wheel" params="lr parent reflectY">
		
		<!-- Wheel link description -->
		<link name="${lr}_wheel">
			<visual>
				<geometry>
					<cylinder length="${wheel_width}" radius="${wheel_radius}"/>
				</geometry>
				<origin rpy="1.57057 0 0"/>
				<material name="black"/>
			</visual>
			<inertial>
				<mass value="${wheel_mass}"/>
				<inertia ixx="${wheel_ixx}" ixy="0.0" ixz="0.0" iyy="${wheel_iyy}" iyz="0.0" izz="${wheel_izz}"/>
			</inertial>
			<collision>
				<geometry>
					<cylinder length="${wheel_width}" radius="${wheel_radius}"/>
				</geometry>
				<origin rpy="1.57057 0 0"/>
			</collision>
		</link>

		<!-- Gazebo description for wheel -->
		<gazebo reference="${lr}_wheel">
			<mu1>1.0</mu1>
			<mu2>1.0</mu2>
			<kp>10000000.0</kp>
			<kd>100.0</kd>
			<minDepth>0.001</minDepth>
		</gazebo>

		<!-- Joint connecting wheel and base link -->
		<joint name="${lr}_wheel_joint" type="continuous">
			<parent link="${parent}"/>
			<child link="${lr}_wheel"/>
			<axis xyz="0 1 0"/>
			<origin xyz="-${chassis_length/4} ${reflectY * (chassis_width/2 + wheel_width/2)} 0"/>
			<limit effort="100" velocity="0.0"/>
		</joint>

		<!-- Gazebo description for wheel_joint -->
		<gazebo reference="${lr}_wheel_joint"/>

		<!-- Transmission for wheel joint -->
		<transmission name="${lr}_wheel_trans">
			<type>transmission_interface/SimpleTransmission</type>
			<joint name="${lr}_wheel_joint">
				<hardwareInterface>EffortJointInterface</hardwareInterface>
			</joint>
			<actuator name="${lr}_motor">
				<mechanicalReduction>1</mechanicalReduction>
			</actuator>
		</transmission>

	</xacro:macro>
</robot>

